[storage]
path = "sota-prov"

[pacman]
sysroot = "sysroot"
os = "myos"

[uptane]
disable_keyid_validation = true
primary_ecu_hardware_id = "qemux86-64"

[provision]
provision_path = "/home/phil/phil-ci-n6.zip"

