[device]
packages_dir = "/tmp/packages_dir"
certificates_directory = "/tmp/sota"
system_info = "system_info.sh"

[tls]
ca_file = "root.crt"
client_certificate = "client.pem"
pkey_file = "pkey.pem"
server = "https://d3db2ce3-848b-4ca1-bd61-f76354601371.tcpgw.prod01.advancedtelematic.com:8000"

[ostree]
sysroot = "/tmp/sysroot"
os = "myos"

[uptane]
metadata_path = "/tmp/sota"
private_key_path = "ecukey.der"
public_key_path = "ecukey.pub"
disable_keyid_validation = true

[provision]
p12_path = "sota_provisioning_credentials.p12"

