[provision]
provision_path = "credentials.zip"
primary_ecu_hardware_id = "local-fake"

[uptane]
polling_sec = 1
secondary_config_file = "posix_secondary_config.json"

[logger]
loglevel = 1

[storage]
path = "storage"

[pacman]
type = "none"
