[tls]
server_url_path = "/var/sota/gateway.url"

[storage]
type = "sqlite"
sqldb_path = "/var/sota/sql.db"
schemas_path = "/usr/lib/sota/schemas"

[import]
tls_cacert_path = "/var/sota/import_root.crt"
tls_clientcert_path = "/var/sota/import_client.pem"
tls_pkey_path = "/var/sota/import_pkey.pem"
