[tls]
certificates_directory = "/var/sota/"
server = "https://5ca9f2ea-9e2b-47d8-836a-0d1910bd577e.tcpgw.prod01.advancedtelematic.com:443"

[uptane]
metadata_path = "/var/sota/metadata"
private_key_path = "ecukey.der"
public_key_path = "ecukey.pub"
