dist: trusty
sudo: false
language: cpp
env:
  - DOCKERFILE=Dockerfile
  - DOCKERFILE=Dockerfile.ubuntu-xenial
services:
  - docker
script:
  - docker build -t advancedtelematic/sota-tools -f ${DOCKERFILE} .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "${TRAVIS_PULL_REQUEST}" == "false" -a "$DOCKERFILE" == "Dockerfile" ] ; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
    docker push advancedtelematic/sota-tools ;
    else
    echo "Not pushing to dockerhub TRAVIS_BRANCH=$TRAVIS_BRANCH DOCKERFILE=$DOCKERFILE" ;
    fi